'use strict';

// Alle øvelser appen kan foreslå.
//
// equipment: redskaber der kræves. En streng betyder "skal have", en liste
//            betyder "mindst én af dem" (fx håndvægt ELLER kettlebell).
// unit:      'reps' (gentagelser), 'seconds' (hold i X sekunder) eller
//            'perSide' (gentagelser pr. side/ben/arm).
// amounts:   grundmængden for styrkeniveau 1–4. `null` = øvelsen foreslås
//            ikke på det niveau (for svær eller for let).
// animation: navnet på animationen i src/renderer/shared/animations.js.
const EXERCISES = [
  // --- Uden udstyr -------------------------------------------------------
  {
    id: 'pushup',
    name: 'Armbøjninger',
    muscleGroup: 'push',
    equipment: [],
    unit: 'reps',
    amounts: [5, 10, 18, 28],
    animation: 'pushup',
    steps: [
      'Placér hænderne lidt bredere end skuldrene.',
      'Hold kroppen helt lige fra hoved til hæle.',
      'Sænk brystet mod gulvet og pres dig op igen.',
    ],
    tip: 'For hårdt? Sæt knæene i gulvet.',
  },
  {
    id: 'kneePushup',
    name: 'Armbøjninger på knæ',
    muscleGroup: 'push',
    equipment: [],
    unit: 'reps',
    amounts: [8, 12, null, null],
    animation: 'kneePushup',
    steps: [
      'Sæt knæene i gulvet og hænderne under skuldrene.',
      'Hold ryggen lige fra knæ til hoved.',
      'Sænk brystet mod gulvet og pres op igen.',
    ],
    tip: 'Spænd maven, så hoften ikke hænger.',
  },
  {
    id: 'squat',
    name: 'Squats',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'reps',
    amounts: [10, 15, 25, 40],
    animation: 'squat',
    steps: [
      'Stå med fødderne i skulderbredde og armene frem.',
      'Skub hoften bagud og bøj i knæene, som om du sætter dig på en stol.',
      'Gå ned, til lårene er vandrette, og rejs dig op igen.',
    ],
    tip: 'Hold hælene i gulvet og knæene over tæerne.',
  },
  {
    id: 'lunge',
    name: 'Udfaldsskridt',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'perSide',
    sideLabel: 'pr. ben',
    amounts: [5, 8, 12, 16],
    animation: 'lunge',
    steps: [
      'Tag et langt skridt frem.',
      'Sænk det bageste knæ, til det næsten rører gulvet.',
      'Pres dig op igen og skift ben.',
    ],
    tip: 'Hold overkroppen oprejst hele vejen.',
  },
  {
    id: 'plank',
    name: 'Planke',
    muscleGroup: 'core',
    equipment: [],
    unit: 'seconds',
    amounts: [20, 30, 50, 75],
    animation: 'plank',
    steps: [
      'Læg underarmene i gulvet med albuerne under skuldrene.',
      'Løft kroppen, så du er helt lige fra hoved til hæle.',
      'Spænd maven og hold positionen.',
    ],
    tip: 'Lad ikke hoften falde ned eller stritte op.',
  },
  {
    id: 'jumpingJack',
    name: 'Sprællemænd',
    muscleGroup: 'cardio',
    equipment: [],
    unit: 'reps',
    amounts: [20, 30, 45, 60],
    animation: 'jumpingJack',
    steps: [
      'Stå med samlede ben og armene ned langs siden.',
      'Hop ud med benene og før armene op over hovedet.',
      'Hop tilbage til start i samme bevægelse.',
    ],
    tip: 'Land blødt på forfoden.',
  },
  {
    id: 'mountainClimber',
    name: 'Mountain climbers',
    muscleGroup: 'cardio',
    equipment: [],
    unit: 'perSide',
    sideLabel: 'pr. ben',
    amounts: [8, 12, 18, 25],
    animation: 'mountainClimber',
    steps: [
      'Start i armbøjningsposition med strakte arme.',
      'Træk skiftevis knæene op mod brystet.',
      'Hold et højt tempo og hoften lav.',
    ],
    tip: 'Hold skuldrene lige over hænderne.',
  },
  {
    id: 'gluteBridge',
    name: 'Hoftehævninger',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'reps',
    amounts: [10, 15, 20, 30],
    animation: 'gluteBridge',
    steps: [
      'Lig på ryggen med bøjede knæ og fødderne i gulvet.',
      'Pres hoften op, til kroppen er lige fra knæ til skuldre.',
      'Klem ballerne sammen i toppen og sænk langsomt.',
    ],
    tip: 'Pres igennem hælene, ikke tæerne.',
  },
  {
    id: 'burpee',
    name: 'Burpees',
    muscleGroup: 'cardio',
    equipment: [],
    unit: 'reps',
    amounts: [null, 6, 10, 15],
    animation: 'burpee',
    steps: [
      'Gå ned i squat og sæt hænderne i gulvet.',
      'Hop fødderne bagud til armbøjningsposition.',
      'Hop fødderne frem igen og hop op med armene over hovedet.',
    ],
    tip: 'Tag den i dit eget tempo – teknik før fart.',
  },
  {
    id: 'wallSit',
    name: 'Vægsid',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'seconds',
    amounts: [20, 35, 50, 75],
    animation: 'wallSit',
    steps: [
      'Stil dig med ryggen mod en væg.',
      'Glid ned, til knæene er bøjet 90 grader.',
      'Hold positionen med ryggen presset mod væggen.',
    ],
    tip: 'Knæene skal være lige over anklerne.',
  },
  {
    id: 'crunch',
    name: 'Mavebøjninger',
    muscleGroup: 'core',
    equipment: [],
    unit: 'reps',
    amounts: [10, 15, 20, 30],
    animation: 'crunch',
    steps: ['Lig på ryggen med bøjede knæ.', 'Rul skuldrene op fra gulvet ved at spænde maven.', 'Sænk langsomt igen.'],
    tip: 'Undgå at hive i nakken – kig op i loftet.',
  },
  {
    id: 'calfRaise',
    name: 'Tåhævninger',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'reps',
    amounts: [15, 20, 30, 40],
    animation: 'calfRaise',
    steps: ['Stå med fødderne i hoftebredde.', 'Løft hælene så højt, du kan.', 'Sænk langsomt ned igen.'],
    tip: 'Stå på et trin for at gøre den sværere.',
  },
  {
    id: 'superman',
    name: 'Superman',
    muscleGroup: 'pull',
    equipment: [],
    unit: 'reps',
    amounts: [8, 12, 15, 20],
    animation: 'superman',
    steps: [
      'Lig på maven med strakte arme foran dig.',
      'Løft arme, bryst og ben fra gulvet på samme tid.',
      'Hold et sekund i toppen og sænk igen.',
    ],
    tip: 'Kig ned i gulvet, så nakken er lang.',
  },

  // --- Pull-up bar ---------------------------------------------------------
  {
    id: 'pullup',
    name: 'Pull-ups',
    muscleGroup: 'pull',
    equipment: ['pullupBar'],
    unit: 'reps',
    amounts: [null, 3, 6, 10],
    animation: 'pullup',
    steps: [
      'Tag fat i stangen med håndfladerne væk fra dig.',
      'Træk dig op, til hagen er over stangen.',
      'Sænk dig kontrolleret helt ned igen.',
    ],
    tip: 'Undgå at svinge – træk skulderbladene ned først.',
  },
  {
    id: 'chinup',
    name: 'Chin-ups',
    muscleGroup: 'pull',
    equipment: ['pullupBar'],
    unit: 'reps',
    amounts: [null, 3, 7, 11],
    animation: 'pullup',
    steps: [
      'Tag fat i stangen med håndfladerne vendt mod dig.',
      'Træk dig op, til hagen er over stangen.',
      'Sænk dig kontrolleret helt ned igen.',
    ],
    tip: 'Underhåndsgrebet bruger biceps ekstra meget.',
  },
  {
    id: 'negativePullup',
    name: 'Negative pull-ups',
    muscleGroup: 'pull',
    equipment: ['pullupBar'],
    unit: 'reps',
    amounts: [3, 4, null, null],
    animation: 'negativePullup',
    steps: [
      'Hop eller træd op, så hagen er over stangen.',
      'Sænk dig så langsomt som muligt – gerne 3–5 sekunder.',
      'Sæt fødderne i gulvet og gentag.',
    ],
    tip: 'Den bedste vej til din første rigtige pull-up.',
  },
  {
    id: 'deadHang',
    name: 'Hæng i stangen',
    muscleGroup: 'pull',
    equipment: ['pullupBar'],
    unit: 'seconds',
    amounts: [15, 25, 35, 50],
    animation: 'deadHang',
    steps: [
      'Tag fat i stangen med strakte arme.',
      'Løft fødderne fra gulvet og hæng stille.',
      'Træk skuldrene lidt ned, væk fra ørerne.',
    ],
    tip: 'Godt for grebet og skuldrene efter lang tid ved skærmen.',
  },
  {
    id: 'hangingKneeRaise',
    name: 'Hængende knæløft',
    muscleGroup: 'core',
    equipment: ['pullupBar'],
    unit: 'reps',
    amounts: [4, 8, 12, 15],
    animation: 'hangingKneeRaise',
    steps: [
      'Hæng i stangen med strakte arme.',
      'Træk knæene op mod brystet med mavemusklerne.',
      'Sænk benene langsomt uden at svinge.',
    ],
    tip: 'Langsomt er hårdere – og bedre.',
  },

  // --- Håndvægte / kettlebell ----------------------------------------------
  {
    id: 'bicepCurl',
    name: 'Biceps curls',
    muscleGroup: 'pull',
    equipment: ['dumbbells'],
    unit: 'reps',
    amounts: [8, 10, 12, 15],
    animation: 'bicepCurl',
    steps: [
      'Stå med en håndvægt i hver hånd og armene strakt.',
      'Bøj albuerne og løft vægtene op mod skuldrene.',
      'Sænk langsomt – hold albuerne ind til kroppen.',
    ],
    tip: 'Vælg en vægt, hvor de sidste gentagelser er hårde.',
  },
  {
    id: 'dumbbellRow',
    name: 'Roning med håndvægt',
    muscleGroup: 'pull',
    equipment: ['dumbbells'],
    unit: 'perSide',
    sideLabel: 'pr. arm',
    amounts: [8, 10, 12, 15],
    animation: 'dumbbellRow',
    steps: [
      'Bøj forover med lige ryg og støt den ene hånd på knæet.',
      'Træk håndvægten op mod hoften med albuen tæt på kroppen.',
      'Sænk kontrolleret, og skift arm efter sættet.',
    ],
    tip: 'Tænk "albuen i lommen" i toppen.',
  },
  {
    id: 'shoulderPress',
    name: 'Skulderpres',
    muscleGroup: 'push',
    equipment: ['dumbbells'],
    unit: 'reps',
    amounts: [6, 8, 12, 15],
    animation: 'shoulderPress',
    steps: [
      'Hold håndvægtene ved skuldrene med albuerne ud til siden.',
      'Pres vægtene op over hovedet, til armene er strakte.',
      'Sænk langsomt ned til skuldrene igen.',
    ],
    tip: 'Spænd maven, så du ikke svajer i ryggen.',
  },
  {
    id: 'lateralRaise',
    name: 'Sideløft',
    muscleGroup: 'push',
    equipment: ['dumbbells'],
    unit: 'reps',
    amounts: [8, 10, 12, 15],
    animation: 'lateralRaise',
    steps: [
      'Stå med en let håndvægt i hver hånd.',
      'Løft armene ud til siden, til de er i skulderhøjde.',
      'Sænk langsomt igen.',
    ],
    tip: 'Brug lette vægte – det er hårdere, end det ser ud.',
  },
  {
    id: 'gobletSquat',
    name: 'Goblet squat',
    muscleGroup: 'legs',
    equipment: [['dumbbells', 'kettlebell']],
    unit: 'reps',
    amounts: [8, 10, 15, 20],
    animation: 'gobletSquat',
    steps: [
      'Hold en håndvægt eller kettlebell ind til brystet.',
      'Gå ned i en dyb squat med ret ryg.',
      'Pres op gennem hælene.',
    ],
    tip: 'Albuerne peger ned mellem knæene i bunden.',
  },
  {
    id: 'kettlebellSwing',
    name: 'Kettlebell swings',
    muscleGroup: 'cardio',
    equipment: ['kettlebell'],
    unit: 'reps',
    amounts: [10, 15, 20, 30],
    animation: 'kettlebellSwing',
    steps: [
      'Stå bredt med kettlebellen mellem fødderne.',
      'Skub hoften bagud og sving klokken ind mellem benene.',
      'Pres hoften frem, så klokken svinger op i brysthøjde.',
    ],
    tip: 'Kraften kommer fra hoften – ikke fra armene.',
  },

  // --- Træningsbænk ----------------------------------------------------------
  {
    id: 'inclinePushup',
    name: 'Skrå armbøjninger',
    muscleGroup: 'push',
    equipment: ['bench'],
    unit: 'reps',
    amounts: [8, 12, 15, null],
    animation: 'inclinePushup',
    steps: [
      'Placér hænderne på kanten af bænken.',
      'Gå baglæns med fødderne, til kroppen er helt lige.',
      'Sænk brystet mod bænken og pres op igen.',
    ],
    tip: 'Jo højere hænderne er, jo lettere er det.',
  },
  {
    id: 'benchDip',
    name: 'Dips på bænk',
    muscleGroup: 'push',
    equipment: ['bench'],
    unit: 'reps',
    amounts: [6, 10, 14, 20],
    animation: 'benchDip',
    steps: [
      'Sæt hænderne på kanten af bænken bag dig.',
      'Bøj albuerne og sænk hoften mod gulvet.',
      'Pres dig op, til armene er strakte.',
    ],
    tip: 'Brug aldrig en kontorstol med hjul.',
  },
  {
    id: 'stepUp',
    name: 'Step-ups',
    muscleGroup: 'legs',
    equipment: ['bench'],
    unit: 'perSide',
    sideLabel: 'pr. ben',
    amounts: [6, 8, 12, 15],
    animation: 'stepUp',
    steps: [
      'Stil den ene fod op på bænken.',
      'Pres dig op, til du står på bænken.',
      'Træd kontrolleret ned, og skift ben efter sættet.',
    ],
    tip: 'Pres med benet på bænken – ikke med det bageste.',
  },
  {
    id: 'splitSquat',
    name: 'Bulgarsk split squat',
    muscleGroup: 'legs',
    equipment: ['bench'],
    unit: 'perSide',
    sideLabel: 'pr. ben',
    amounts: [null, 6, 8, 12],
    animation: 'splitSquat',
    steps: [
      'Læg den bageste fod op på bænken bag dig.',
      'Sænk dig ned, til det forreste lår er næsten vandret.',
      'Pres op gennem den forreste hæl.',
    ],
    tip: 'Find balancen først – tag gerne fat i noget.',
  },
  {
    id: 'benchPress',
    name: 'Bænkpres med håndvægte',
    muscleGroup: 'push',
    equipment: ['dumbbells', 'bench'],
    unit: 'reps',
    amounts: [8, 10, 12, 15],
    animation: 'benchPress',
    steps: [
      'Lig på bænken med en håndvægt i hver hånd ved brystet.',
      'Pres vægtene op, til armene er strakte.',
      'Sænk kontrolleret ned til brystet igen.',
    ],
    tip: 'Hold fødderne plantet i gulvet.',
  },

  // --- Elastikker --------------------------------------------------------------
  {
    id: 'bandPullApart',
    name: 'Elastik pull-aparts',
    muscleGroup: 'pull',
    equipment: ['resistanceBand'],
    unit: 'reps',
    amounts: [10, 15, 20, 25],
    animation: 'bandPullApart',
    steps: [
      'Hold elastikken foran dig i skulderhøjde.',
      'Træk elastikken fra hinanden ud til siderne.',
      'Før armene langsomt tilbage.',
    ],
    tip: 'Perfekt mod "gamer-skuldre" – klem skulderbladene sammen.',
  },
  {
    id: 'bandCurl',
    name: 'Biceps curls med elastik',
    muscleGroup: 'pull',
    equipment: ['resistanceBand'],
    unit: 'reps',
    amounts: [10, 15, 20, 25],
    animation: 'bandCurl',
    steps: [
      'Stå på midten af elastikken og hold i enderne.',
      'Bøj albuerne og træk hænderne op mod skuldrene.',
      'Sænk langsomt igen.',
    ],
    tip: 'Stå bredere for mere modstand.',
  },
];

module.exports = { EXERCISES };
