'use strict';

// Alle øvelser appen kan foreslå.
//
// muscleGroup: se MUSCLE_GROUPS i catalog.js. Bestemmer også fokusområdet.
// extraFocus: (valgfri) ekstra fokusområder, fx pull-ups der også træner arme.
// equipment: redskaber der kræves. En streng betyder "skal have", en liste
//            betyder "mindst én af dem" (fx håndvægt ELLER kettlebell).
// unit:      'reps' (gentagelser), 'seconds' (hold i X sekunder) eller
//            'perSide' (gentagelser pr. side/ben/arm).
// difficulty: 1 = let, 2 = middel, 3 = svær (vises i opsætningen).
// amounts:   grundmængden for styrkeniveau 1–4. `null` = øvelsen foreslås
//            ikke på det niveau (for svær eller for let).
// animation: navnet på animationen i src/renderer/shared/animations.js.
const EXERCISES = [
  // --- Uden udstyr -------------------------------------------------------
  {
    id: 'pushup',
    name: 'Armbøjninger',
    muscleGroup: 'chest',
    equipment: [],
    unit: 'reps',
    difficulty: 2,
    amounts: [5, 10, 18, 28],
    animation: 'pushup',
    steps: [
      'Placér hænderne lidt bredere end skuldrene.',
      'Hold kroppen helt lige fra hoved til hæle.',
      'Sænk brystet mod gulvet og pres dig op igen.',
    ],
    tip: 'For hårdt? Sæt knæene i gulvet.',
  },
  {
    id: 'kneePushup',
    name: 'Armbøjninger på knæ',
    muscleGroup: 'chest',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 12, null, null],
    animation: 'kneePushup',
    steps: [
      'Sæt knæene i gulvet og hænderne under skuldrene.',
      'Hold ryggen lige fra knæ til hoved.',
      'Sænk brystet mod gulvet og pres op igen.',
    ],
    tip: 'Spænd maven, så hoften ikke hænger.',
  },
  {
    id: 'squat',
    name: 'Squats',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 15, 25, 40],
    animation: 'squat',
    steps: [
      'Stå med fødderne i skulderbredde og armene frem.',
      'Skub hoften bagud og bøj i knæene, som om du sætter dig på en stol.',
      'Gå ned, til lårene er vandrette, og rejs dig op igen.',
    ],
    tip: 'Hold hælene i gulvet og knæene over tæerne.',
  },
  {
    id: 'lunge',
    name: 'Udfaldsskridt',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'perSide',
    sideLabel: 'pr. ben',
    difficulty: 2,
    amounts: [5, 8, 12, 16],
    animation: 'lunge',
    steps: [
      'Tag et langt skridt frem.',
      'Sænk det bageste knæ, til det næsten rører gulvet.',
      'Pres dig op igen og skift ben.',
    ],
    tip: 'Hold overkroppen oprejst hele vejen.',
  },
  {
    id: 'plank',
    name: 'Planke',
    muscleGroup: 'core',
    equipment: [],
    unit: 'seconds',
    difficulty: 1,
    amounts: [20, 30, 50, 75],
    animation: 'plank',
    steps: [
      'Læg underarmene i gulvet med albuerne under skuldrene.',
      'Løft kroppen, så du er helt lige fra hoved til hæle.',
      'Spænd maven og hold positionen.',
    ],
    tip: 'Lad ikke hoften falde ned eller stritte op.',
  },
  {
    id: 'jumpingJack',
    name: 'Sprællemænd',
    muscleGroup: 'cardio',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [20, 30, 45, 60],
    animation: 'jumpingJack',
    steps: [
      'Stå med samlede ben og armene ned langs siden.',
      'Hop ud med benene og før armene op over hovedet.',
      'Hop tilbage til start i samme bevægelse.',
    ],
    tip: 'Land blødt på forfoden.',
  },
  {
    id: 'mountainClimber',
    name: 'Mountain climbers',
    muscleGroup: 'cardio',
    equipment: [],
    unit: 'perSide',
    sideLabel: 'pr. ben',
    difficulty: 2,
    amounts: [8, 12, 18, 25],
    animation: 'mountainClimber',
    steps: [
      'Start i armbøjningsposition med strakte arme.',
      'Træk skiftevis knæene op mod brystet.',
      'Hold et højt tempo og hoften lav.',
    ],
    tip: 'Hold skuldrene lige over hænderne.',
  },
  {
    id: 'gluteBridge',
    name: 'Hoftehævninger',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 15, 20, 30],
    animation: 'gluteBridge',
    steps: [
      'Lig på ryggen med bøjede knæ og fødderne i gulvet.',
      'Pres hoften op, til kroppen er lige fra knæ til skuldre.',
      'Klem ballerne sammen i toppen og sænk langsomt.',
    ],
    tip: 'Pres igennem hælene, ikke tæerne.',
  },
  {
    id: 'burpee',
    name: 'Burpees',
    muscleGroup: 'cardio',
    extraFocus: ['chestShoulders'],
    equipment: [],
    unit: 'reps',
    difficulty: 3,
    amounts: [null, 6, 10, 15],
    animation: 'burpee',
    steps: [
      'Gå ned i squat og sæt hænderne i gulvet.',
      'Hop fødderne bagud til armbøjningsposition.',
      'Hop fødderne frem igen og hop op med armene over hovedet.',
    ],
    tip: 'Tag den i dit eget tempo – teknik før fart.',
  },
  {
    id: 'wallSit',
    name: 'Vægsid',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'seconds',
    difficulty: 2,
    amounts: [20, 35, 50, 75],
    animation: 'wallSit',
    steps: [
      'Stil dig med ryggen mod en væg.',
      'Glid ned, til knæene er bøjet 90 grader.',
      'Hold positionen med ryggen presset mod væggen.',
    ],
    tip: 'Knæene skal være lige over anklerne.',
  },
  {
    id: 'crunch',
    name: 'Mavebøjninger',
    muscleGroup: 'core',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 15, 20, 30],
    animation: 'crunch',
    steps: ['Lig på ryggen med bøjede knæ.', 'Rul skuldrene op fra gulvet ved at spænde maven.', 'Sænk langsomt igen.'],
    tip: 'Undgå at hive i nakken – kig op i loftet.',
  },
  {
    id: 'calfRaise',
    name: 'Tåhævninger',
    muscleGroup: 'legs',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [15, 20, 30, 40],
    animation: 'calfRaise',
    steps: ['Stå med fødderne i hoftebredde.', 'Løft hælene så højt, du kan.', 'Sænk langsomt ned igen.'],
    tip: 'Stå på et trin for at gøre den sværere.',
  },
  {
    id: 'superman',
    name: 'Superman',
    muscleGroup: 'back',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 12, 15, 20],
    animation: 'superman',
    steps: [
      'Lig på maven med strakte arme foran dig.',
      'Løft arme, bryst og ben fra gulvet på samme tid.',
      'Hold et sekund i toppen og sænk igen.',
    ],
    tip: 'Kig ned i gulvet, så nakken er lang.',
  },

  {
    id: 'diamondPushup',
    name: 'Diamant-armbøjninger',
    muscleGroup: 'triceps',
    extraFocus: ['chestShoulders'],
    equipment: [],
    unit: 'reps',
    difficulty: 3,
    amounts: [3, 6, 10, 15],
    animation: 'pushup',
    steps: [
      'Sæt hænderne tæt sammen under brystet, så fingrene danner en diamant.',
      'Hold albuerne tæt ind til kroppen.',
      'Sænk brystet mod hænderne og pres op igen.',
    ],
    tip: 'For hårdt? Lav dem med knæene i gulvet.',
  },
  {
    id: 'chinTuck',
    name: 'Hagetræk (chin tucks)',
    muscleGroup: 'neck',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'chinTuck',
    steps: [
      'Sid eller stå med rank ryg og kig lige frem.',
      'Skub hagen lige bagud, så du får "dobbelthage" – uden at kigge ned.',
      'Hold i 3 sekunder, og slap af.',
    ],
    tip: 'Perfekt mod "gamer-nakke" – kan laves i stolen.',
  },
  {
    id: 'wallAngel',
    name: 'Vægengle',
    muscleGroup: 'posture',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [6, 8, 10, 12],
    animation: 'wallAngel',
    steps: [
      'Stå med ryg, hoved og baller mod en væg.',
      'Løft armene til "målstolpe" med albuer og håndled mod væggen.',
      'Glid armene langsomt op over hovedet og ned igen.',
    ],
    tip: 'Gå kun så højt, du kan uden at slippe væggen.',
  },

  // --- Pull-up bar ---------------------------------------------------------
  {
    id: 'pullup',
    name: 'Pull-ups',
    muscleGroup: 'back',
    extraFocus: ['arms'],
    equipment: ['pullupBar'],
    unit: 'reps',
    difficulty: 3,
    amounts: [null, 3, 6, 10],
    animation: 'pullup',
    steps: [
      'Tag fat i stangen med håndfladerne væk fra dig.',
      'Træk dig op, til hagen er over stangen.',
      'Sænk dig kontrolleret helt ned igen.',
    ],
    tip: 'Undgå at svinge – træk skulderbladene ned først.',
  },
  {
    id: 'chinup',
    name: 'Chin-ups',
    muscleGroup: 'back',
    extraFocus: ['arms'],
    equipment: ['pullupBar'],
    unit: 'reps',
    difficulty: 3,
    amounts: [null, 3, 7, 11],
    animation: 'pullup',
    steps: [
      'Tag fat i stangen med håndfladerne vendt mod dig.',
      'Træk dig op, til hagen er over stangen.',
      'Sænk dig kontrolleret helt ned igen.',
    ],
    tip: 'Underhåndsgrebet bruger biceps ekstra meget.',
  },
  {
    id: 'negativePullup',
    name: 'Negative pull-ups',
    muscleGroup: 'back',
    extraFocus: ['arms'],
    equipment: ['pullupBar'],
    unit: 'reps',
    difficulty: 2,
    amounts: [3, 4, null, null],
    animation: 'negativePullup',
    steps: [
      'Hop eller træd op, så hagen er over stangen.',
      'Sænk dig så langsomt som muligt – gerne 3–5 sekunder.',
      'Sæt fødderne i gulvet og gentag.',
    ],
    tip: 'Den bedste vej til din første rigtige pull-up.',
  },
  {
    id: 'deadHang',
    name: 'Hæng i stangen',
    muscleGroup: 'back',
    extraFocus: ['arms'],
    equipment: ['pullupBar'],
    unit: 'seconds',
    difficulty: 2,
    amounts: [15, 25, 35, 50],
    animation: 'deadHang',
    steps: [
      'Tag fat i stangen med strakte arme.',
      'Løft fødderne fra gulvet og hæng stille.',
      'Træk skuldrene lidt ned, væk fra ørerne.',
    ],
    tip: 'Godt for grebet og skuldrene efter lang tid ved skærmen.',
  },
  {
    id: 'hangingKneeRaise',
    name: 'Hængende knæløft',
    muscleGroup: 'core',
    equipment: ['pullupBar'],
    unit: 'reps',
    difficulty: 2,
    amounts: [4, 8, 12, 15],
    animation: 'hangingKneeRaise',
    steps: [
      'Hæng i stangen med strakte arme.',
      'Træk knæene op mod brystet med mavemusklerne.',
      'Sænk benene langsomt uden at svinge.',
    ],
    tip: 'Langsomt er hårdere – og bedre.',
  },

  // --- Håndvægte / kettlebell ----------------------------------------------
  {
    id: 'bicepCurl',
    name: 'Biceps curls',
    muscleGroup: 'biceps',
    equipment: ['dumbbells'],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'bicepCurl',
    steps: [
      'Stå med en håndvægt i hver hånd og armene strakt.',
      'Bøj albuerne og løft vægtene op mod skuldrene.',
      'Sænk langsomt – hold albuerne ind til kroppen.',
    ],
    tip: 'Vælg en vægt, hvor de sidste gentagelser er hårde.',
  },
  {
    id: 'dumbbellRow',
    name: 'Roning med håndvægt',
    muscleGroup: 'back',
    equipment: ['dumbbells'],
    unit: 'perSide',
    sideLabel: 'pr. arm',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'dumbbellRow',
    steps: [
      'Bøj forover med lige ryg og støt den ene hånd på knæet.',
      'Træk håndvægten op mod hoften med albuen tæt på kroppen.',
      'Sænk kontrolleret, og skift arm efter sættet.',
    ],
    tip: 'Tænk "albuen i lommen" i toppen.',
  },
  {
    id: 'shoulderPress',
    name: 'Skulderpres',
    muscleGroup: 'shoulders',
    equipment: ['dumbbells'],
    unit: 'reps',
    difficulty: 2,
    amounts: [6, 8, 12, 15],
    animation: 'shoulderPress',
    steps: [
      'Hold håndvægtene ved skuldrene med albuerne ud til siden.',
      'Pres vægtene op over hovedet, til armene er strakte.',
      'Sænk langsomt ned til skuldrene igen.',
    ],
    tip: 'Spænd maven, så du ikke svajer i ryggen.',
  },
  {
    id: 'lateralRaise',
    name: 'Sideløft',
    muscleGroup: 'shoulders',
    equipment: ['dumbbells'],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'lateralRaise',
    steps: [
      'Stå med en let håndvægt i hver hånd.',
      'Løft armene ud til siden, til de er i skulderhøjde.',
      'Sænk langsomt igen.',
    ],
    tip: 'Brug lette vægte – det er hårdere, end det ser ud.',
  },
  {
    id: 'gobletSquat',
    name: 'Goblet squat',
    muscleGroup: 'legs',
    equipment: [['dumbbells', 'kettlebell']],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 15, 20],
    animation: 'gobletSquat',
    steps: [
      'Hold en håndvægt eller kettlebell ind til brystet.',
      'Gå ned i en dyb squat med ret ryg.',
      'Pres op gennem hælene.',
    ],
    tip: 'Albuerne peger ned mellem knæene i bunden.',
  },
  {
    id: 'kettlebellSwing',
    name: 'Kettlebell swings',
    muscleGroup: 'legs',
    equipment: ['kettlebell'],
    unit: 'reps',
    difficulty: 2,
    amounts: [10, 15, 20, 30],
    animation: 'kettlebellSwing',
    steps: [
      'Stå bredt med kettlebellen mellem fødderne.',
      'Skub hoften bagud og sving klokken ind mellem benene.',
      'Pres hoften frem, så klokken svinger op i brysthøjde.',
    ],
    tip: 'Kraften kommer fra hoften – ikke fra armene.',
  },

  // --- Træningsbænk ----------------------------------------------------------
  {
    id: 'inclinePushup',
    name: 'Skrå armbøjninger',
    muscleGroup: 'chest',
    equipment: ['bench'],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 12, 15, null],
    animation: 'inclinePushup',
    steps: [
      'Placér hænderne på kanten af bænken.',
      'Gå baglæns med fødderne, til kroppen er helt lige.',
      'Sænk brystet mod bænken og pres op igen.',
    ],
    tip: 'Jo højere hænderne er, jo lettere er det.',
  },
  {
    id: 'benchDip',
    name: 'Dips på bænk',
    muscleGroup: 'triceps',
    extraFocus: ['chestShoulders'],
    equipment: ['bench'],
    unit: 'reps',
    difficulty: 2,
    amounts: [6, 10, 14, 20],
    animation: 'benchDip',
    steps: [
      'Sæt hænderne på kanten af bænken bag dig.',
      'Bøj albuerne og sænk hoften mod gulvet.',
      'Pres dig op, til armene er strakte.',
    ],
    tip: 'Brug aldrig en kontorstol med hjul.',
  },
  {
    id: 'stepUp',
    name: 'Step-ups',
    muscleGroup: 'legs',
    equipment: ['bench'],
    unit: 'perSide',
    sideLabel: 'pr. ben',
    difficulty: 1,
    amounts: [6, 8, 12, 15],
    animation: 'stepUp',
    steps: [
      'Stil den ene fod op på bænken.',
      'Pres dig op, til du står på bænken.',
      'Træd kontrolleret ned, og skift ben efter sættet.',
    ],
    tip: 'Pres med benet på bænken – ikke med det bageste.',
  },
  {
    id: 'splitSquat',
    name: 'Bulgarsk split squat',
    muscleGroup: 'legs',
    equipment: ['bench'],
    unit: 'perSide',
    sideLabel: 'pr. ben',
    difficulty: 3,
    amounts: [null, 6, 8, 12],
    animation: 'splitSquat',
    steps: [
      'Læg den bageste fod op på bænken bag dig.',
      'Sænk dig ned, til det forreste lår er næsten vandret.',
      'Pres op gennem den forreste hæl.',
    ],
    tip: 'Find balancen først – tag gerne fat i noget.',
  },
  {
    id: 'benchPress',
    name: 'Bænkpres med håndvægte',
    muscleGroup: 'chest',
    equipment: ['dumbbells', 'bench'],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 12, 15],
    animation: 'benchPress',
    steps: [
      'Lig på bænken med en håndvægt i hver hånd ved brystet.',
      'Pres vægtene op, til armene er strakte.',
      'Sænk kontrolleret ned til brystet igen.',
    ],
    tip: 'Hold fødderne plantet i gulvet.',
  },

  // --- Elastikker --------------------------------------------------------------
  {
    id: 'bandPullApart',
    name: 'Elastik pull-aparts',
    muscleGroup: 'posture',
    equipment: ['resistanceBand'],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 15, 20, 25],
    animation: 'bandPullApart',
    steps: [
      'Hold elastikken foran dig i skulderhøjde.',
      'Træk elastikken fra hinanden ud til siderne.',
      'Før armene langsomt tilbage.',
    ],
    tip: 'Perfekt mod "gamer-skuldre" – klem skulderbladene sammen.',
  },
  {
    id: 'bandCurl',
    name: 'Biceps curls med elastik',
    muscleGroup: 'biceps',
    equipment: ['resistanceBand'],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 15, 20, 25],
    animation: 'bandCurl',
    steps: [
      'Stå på midten af elastikken og hold i enderne.',
      'Bøj albuerne og træk hænderne op mod skuldrene.',
      'Sænk langsomt igen.',
    ],
    tip: 'Stå bredere for mere modstand.',
  },

  // --- Nakke og holdning (bænk og vægte) ---------------------------------------
  {
    id: 'neckCurl',
    name: 'Nakkecurls',
    muscleGroup: 'neck',
    equipment: ['bench', ['dumbbells', 'barbell']],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 12, 15, 20],
    animation: 'neckCurl',
    steps: [
      'Lig på ryggen på bænken med hovedet ud over kanten.',
      'Hold en let vægtskive eller håndvægt på panden – med et håndklæde imellem.',
      'Før hagen op mod brystet, og sænk langsomt igen.',
    ],
    tip: 'Start meget let – nakken skal vænnes til det.',
  },
  {
    id: 'neckExtension',
    name: 'Nakkeløft',
    muscleGroup: 'neck',
    equipment: ['bench'],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 12, 15, 20],
    animation: 'neckExtension',
    steps: [
      'Lig på maven på bænken med hovedet ud over kanten.',
      'Lad hovedet hænge roligt ned mod gulvet.',
      'Løft hovedet, til du kigger lige frem, og sænk langsomt.',
    ],
    tip: 'Gør den sværere med en let vægtskive på baghovedet.',
  },
  {
    id: 'proneYRaise',
    name: 'Y-løft på skråbænk',
    muscleGroup: 'posture',
    equipment: ['bench', 'dumbbells'],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'proneYRaise',
    steps: [
      'Lig på maven på en skråtstillet bænk med en let håndvægt i hver hånd.',
      'Løft armene skråt frem og op, så kroppen danner et Y.',
      'Klem skulderbladene ned og sammen, og sænk langsomt.',
    ],
    tip: 'Brug meget lette vægte – det er musklerne mellem skulderbladene, der skal arbejde.',
  },
  {
    id: 'chestSupportedRow',
    name: 'Roning på skråbænk',
    muscleGroup: 'back',
    equipment: ['bench', 'dumbbells'],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'chestSupportedRow',
    steps: [
      'Lig på maven på en skråtstillet bænk med en håndvægt i hver hånd.',
      'Træk vægtene op mod ribbenene med albuerne tæt på kroppen.',
      'Klem skulderbladene sammen i toppen, og sænk langsomt.',
    ],
    tip: 'Bænken holder ryggen stabil, så du kan fokusere på skulderbladene.',
  },
  {
    id: 'preacherCurl',
    name: 'Preacher curls',
    muscleGroup: 'biceps',
    equipment: ['bench', ['dumbbells', 'barbell']],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'preacherCurl',
    steps: [
      'Læg overarmen hen over bænkens skråtstillede ryglæn.',
      'Bøj albuen, og curl vægten op mod skulderen.',
      'Sænk langsomt, til armen er næsten strakt.',
    ],
    tip: 'Lad overarmen blive liggende på puden hele tiden.',
  },

  // --- Vægtstang ---------------------------------------------------------------
  {
    id: 'barbellCurl',
    name: 'Curls med vægtstang',
    muscleGroup: 'biceps',
    equipment: ['barbell'],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 12, 15],
    animation: 'barbellCurl',
    steps: [
      'Hold stangen i skulderbredde med underhåndsgreb.',
      'Curl stangen op mod brystet med albuerne ind til kroppen.',
      'Sænk langsomt, til armene er strakte.',
    ],
    tip: 'Undgå at svinge med ryggen.',
  },
  {
    id: 'barbellRow',
    name: 'Roning med vægtstang',
    muscleGroup: 'back',
    equipment: ['barbell'],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 12, 12],
    animation: 'barbellRow',
    steps: [
      'Bøj forover med lige ryg og let bøjede knæ.',
      'Træk stangen op mod maven.',
      'Sænk kontrolleret, til armene er strakte.',
    ],
    tip: 'Hold ryggen lige – ikke krum.',
  },
  {
    id: 'overheadPress',
    name: 'Skulderpres med vægtstang',
    muscleGroup: 'shoulders',
    equipment: ['barbell'],
    unit: 'reps',
    difficulty: 2,
    amounts: [6, 8, 10, 12],
    animation: 'overheadPress',
    steps: [
      'Hold stangen foran skuldrene med albuerne lidt fremme.',
      'Pres stangen lige op over hovedet.',
      'Sænk den kontrolleret til skuldrene igen.',
    ],
    tip: 'Spænd balder og mave, så du ikke svajer i ryggen.',
  },
  {
    id: 'romanianDeadlift',
    name: 'Rumænsk dødløft',
    muscleGroup: 'legs',
    equipment: ['barbell'],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 12, 12],
    animation: 'romanianDeadlift',
    steps: [
      'Stå med stangen foran lårene og let bøjede knæ.',
      'Skub hoften bagud, og før stangen ned langs benene med lige ryg.',
      'Stop, når baglårene strækker, og rejs dig op.',
    ],
    tip: 'Stangen skal holde sig tæt på benene hele vejen.',
  },
  {
    id: 'barbellBenchPress',
    name: 'Bænkpres med vægtstang',
    muscleGroup: 'chest',
    equipment: ['bench', 'barbell'],
    unit: 'reps',
    difficulty: 3,
    amounts: [6, 8, 10, 12],
    animation: 'barbellBenchPress',
    steps: [
      'Lig på bænken med øjnene lige under stangen.',
      'Sænk stangen kontrolleret ned til brystet.',
      'Pres den op, til armene er strakte.',
    ],
    tip: 'Brug stativ med sikkerhedsstænger eller en makker – tag aldrig tungt alene.',
  },

  // --- Underarme og greb -------------------------------------------------------
  {
    id: 'wristStretch',
    name: 'Håndledsstræk',
    muscleGroup: 'forearms',
    equipment: [],
    unit: 'seconds',
    difficulty: 1,
    amounts: [20, 30, 30, 40],
    animation: 'wristStretch',
    steps: [
      'Stræk den ene arm frem med fingrene pegende opad.',
      'Træk forsigtigt fingrene bagud med den anden hånd.',
      'Vend hånden, så fingrene peger nedad, og stræk igen. Skift arm halvvejs.',
    ],
    tip: 'Godt for musearmen efter lange sessioner.',
  },
  {
    id: 'wristCurl',
    name: 'Håndledscurls',
    muscleGroup: 'forearms',
    equipment: [['dumbbells', 'barbell']],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 12, 15, 20],
    animation: 'wristCurl',
    steps: [
      'Sid med underarmene på lårene og håndfladerne opad.',
      'Lad vægten rulle ned mod fingerspidserne.',
      'Bøj håndleddene, og løft vægten så højt, du kan.',
    ],
    tip: 'Kun håndleddene bevæger sig – underarmene ligger stille.',
  },
  {
    id: 'reverseWristCurl',
    name: 'Omvendte håndledscurls',
    muscleGroup: 'forearms',
    equipment: [['dumbbells', 'barbell']],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 12, 15, 20],
    animation: 'reverseWristCurl',
    steps: [
      'Sid med underarmene på lårene og håndfladerne nedad.',
      'Sænk vægten langsomt ved at bøje håndleddene ned.',
      'Løft vægten ved at bøje håndleddene op.',
    ],
    tip: 'Brug en lettere vægt end til almindelige håndledscurls.',
  },
  {
    id: 'hammerCurl',
    name: 'Hammercurls',
    muscleGroup: 'forearms',
    equipment: ['dumbbells'],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'bicepCurl',
    steps: [
      'Hold håndvægtene med tommelfingrene opad, som en hammer.',
      'Curl vægtene op mod skuldrene uden at dreje håndleddene.',
      'Sænk langsomt.',
    ],
    tip: 'Rammer både biceps og den store muskel oven på underarmen.',
  },
  {
    id: 'reverseCurl',
    name: 'Omvendte curls med vægtstang',
    muscleGroup: 'forearms',
    equipment: ['barbell'],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 12, 15],
    animation: 'barbellCurl',
    steps: [
      'Hold stangen med overhåndsgreb, så knoerne peger opad.',
      'Curl stangen op mod brystet med albuerne ind til kroppen.',
      'Sænk langsomt.',
    ],
    tip: 'Brug en lettere vægt end til almindelige curls.',
  },
  {
    id: 'farmersHold',
    name: "Farmer's hold",
    muscleGroup: 'forearms',
    equipment: [['dumbbells', 'kettlebell']],
    unit: 'seconds',
    difficulty: 1,
    amounts: [20, 30, 40, 60],
    animation: 'farmersHold',
    steps: [
      'Tag en tung håndvægt eller kettlebell i hver hånd.',
      'Stå rank med skuldrene trukket ned og tilbage.',
      'Hold så længe, tiden siger – eller gå rundt i rummet imens.',
    ],
    tip: 'Klem hårdt om håndtagene – det er grebet, der trænes.',
  },
  // --- Flere øvelser uden udstyr -------------------------------------------
  {
    id: 'pikePushup',
    name: 'Pike push-ups',
    muscleGroup: 'shoulders',
    equipment: [],
    unit: 'reps',
    difficulty: 3,
    amounts: [null, 5, 8, 12],
    animation: 'pikePushup',
    steps: [
      'Stå i armbøjningsposition, og gå med fødderne frem, så hoften kommer højt op.',
      'Bøj albuerne, og sænk hovedet ned mod gulvet lige foran hænderne.',
      'Pres dig op igen, til armene er strakte.',
    ],
    tip: 'Jo tættere fødderne er på hænderne, jo mere rammer det skuldrene.',
  },
  {
    id: 'floorYRaise',
    name: 'Y-løft på gulvet',
    muscleGroup: 'posture',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [6, 8, 10, 12],
    animation: 'floorYRaise',
    steps: [
      'Lig på maven med armene strakt frem i et Y og tommelfingrene opad.',
      'Løft armene fra gulvet ved at trække skulderbladene ned og sammen.',
      'Hold 2 sekunder, og sænk langsomt.',
    ],
    tip: 'Kig ned i gulvet, så nakken holdes lang.',
  },
  {
    id: 'wallChestStretch',
    name: 'Brystudstrækning ved væggen',
    muscleGroup: 'posture',
    equipment: [],
    unit: 'seconds',
    difficulty: 1,
    amounts: [20, 30, 30, 40],
    animation: 'wallChestStretch',
    steps: [
      'Stå ved en væg eller en dørkarm, og læg hånden mod den i skulderhøjde bag dig.',
      'Tag et lille skridt frem, og drej let væk fra armen, til det strækker i brystet.',
      'Hold stillingen – tag halvdelen af tiden på hver arm.',
    ],
    tip: 'God modvægt til mange timer foran skærmen med skuldrene rullet frem.',
  },
  {
    id: 'supineNeckLift',
    name: 'Nakkeløft liggende',
    muscleGroup: 'neck',
    equipment: [],
    unit: 'reps',
    difficulty: 1,
    amounts: [6, 8, 10, 12],
    animation: 'supineNeckLift',
    steps: [
      'Lig på ryggen med bøjede ben.',
      'Træk hagen ind, som om du laver dobbelthage.',
      'Løft hovedet et par centimeter fra gulvet, hold 2 sekunder, og sænk igen.',
    ],
    tip: 'Hold hagen inde hele tiden – det er de dybe nakkemuskler, der skal arbejde.',
  },
  {
    id: 'legRaise',
    name: 'Benløft',
    muscleGroup: 'core',
    equipment: [],
    unit: 'reps',
    difficulty: 2,
    amounts: [6, 10, 14, 18],
    animation: 'legRaise',
    steps: [
      'Lig på ryggen med armene langs siden.',
      'Løft de strakte ben op, til de peger mod loftet.',
      'Sænk dem langsomt, til de næsten rører gulvet.',
    ],
    tip: 'Pres lænden ned i gulvet hele vejen. Bøj knæene, hvis den løfter sig.',
  },
  {
    id: 'deadBug',
    name: 'Dead bug',
    muscleGroup: 'core',
    equipment: [],
    unit: 'perSide',
    sideLabel: 'pr. side',
    difficulty: 1,
    amounts: [5, 6, 8, 10],
    animation: 'deadBug',
    steps: [
      'Lig på ryggen med armene mod loftet og hofte og knæ bøjet 90 grader.',
      'Stræk den ene arm bagud og det modsatte ben frem, lige over gulvet.',
      'Kom tilbage, og skift side.',
    ],
    tip: 'Lænden skal blive i gulvet. Gå langsomt.',
  },
  {
    id: 'birdDog',
    name: 'Bird dog',
    muscleGroup: 'core',
    extraFocus: ['backPosture'],
    equipment: [],
    unit: 'perSide',
    sideLabel: 'pr. side',
    difficulty: 1,
    amounts: [5, 6, 8, 10],
    animation: 'birdDog',
    steps: [
      'Stå på alle fire med hænderne under skuldrene og knæene under hoften.',
      'Stræk den ene arm frem og det modsatte ben bagud, til de er i linje med ryggen.',
      'Hold 2 sekunder, kom tilbage, og skift side.',
    ],
    tip: 'Forestil dig et glas vand på lænden – det må ikke vælte.',
  },
  {
    id: 'sidePlank',
    name: 'Sideplanke',
    muscleGroup: 'core',
    equipment: [],
    unit: 'seconds',
    difficulty: 2,
    amounts: [15, 20, 30, 45],
    animation: 'sidePlank',
    steps: [
      'Lig på siden med albuen under skulderen og fødderne oven på hinanden.',
      'Løft hoften, så kroppen er lige fra hoved til fødder.',
      'Hold – tag halvdelen af tiden på hver side.',
    ],
    tip: 'For hårdt? Sæt det nederste knæ i gulvet.',
  },
  {
    id: 'jumpSquat',
    name: 'Squathop',
    muscleGroup: 'cardio',
    equipment: [],
    unit: 'reps',
    difficulty: 2,
    amounts: [null, 8, 12, 18],
    animation: 'jumpSquat',
    steps: [
      'Gå ned i en squat med armene frem.',
      'Hop så højt du kan, og sving armene ned.',
      'Land blødt på forfoden, og gå direkte ned i næste squat.',
    ],
    tip: 'Land stille – så bruger du musklerne i stedet for leddene.',
  },
  {
    id: 'highKnees',
    name: 'Høje knæ',
    muscleGroup: 'cardio',
    equipment: [],
    unit: 'seconds',
    difficulty: 1,
    amounts: [20, 30, 40, 45],
    animation: 'highKnees',
    steps: ['Løb på stedet.', 'Træk knæene op til hoftehøjde, og sving armene med.', 'Hold tempoet højt hele tiden.'],
    tip: 'Bliv på forfoden, og hold overkroppen rank.',
  },

  // --- Flere øvelser med udstyr ----------------------------------------------
  {
    id: 'declinePushup',
    name: 'Armbøjninger med fødderne på bænken',
    muscleGroup: 'chest',
    equipment: ['bench'],
    unit: 'reps',
    difficulty: 3,
    amounts: [null, 6, 10, 15],
    animation: 'declinePushup',
    steps: [
      'Sæt fødderne op på bænken og hænderne i gulvet lidt bredere end skuldrene.',
      'Hold kroppen helt lige.',
      'Sænk brystet mod gulvet, og pres dig op igen.',
    ],
    tip: 'Rammer den øverste del af brystet og skuldrene mere end almindelige armbøjninger.',
  },
  {
    id: 'hipThrust',
    name: 'Hip thrust',
    muscleGroup: 'legs',
    equipment: ['bench'],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 12, 15, 20],
    animation: 'hipThrust',
    steps: [
      'Sid på gulvet med skulderbladene mod kanten af bænken og fødderne i gulvet.',
      'Pres gennem hælene, og løft hoften, til kroppen er vandret fra knæ til skuldre.',
      'Klem ballerne i toppen, og sænk langsomt.',
    ],
    tip: 'For let? Læg en håndvægt på hoften.',
  },
  {
    id: 'frontRaise',
    name: 'Frontløft',
    muscleGroup: 'shoulders',
    equipment: ['dumbbells'],
    unit: 'reps',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'frontRaise',
    steps: [
      'Stå med en håndvægt i hver hånd foran lårene.',
      'Løft armene strakt frem til skulderhøjde.',
      'Sænk langsomt igen.',
    ],
    tip: 'Brug en let vægt, og sving ikke med kroppen.',
  },
  {
    id: 'dumbbellPullover',
    name: 'Pullover med håndvægt',
    muscleGroup: 'chest',
    extraFocus: ['backPosture'],
    equipment: ['bench', 'dumbbells'],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 12, 15],
    animation: 'dumbbellPullover',
    steps: [
      'Lig på bænken, og hold én håndvægt med begge hænder over brystet.',
      'Sænk vægten i en bue bagud over hovedet med let bøjede albuer.',
      'Træk den tilbage over brystet.',
    ],
    tip: 'Gå kun så langt ned, som skuldrene kan lide.',
  },
  {
    id: 'skullCrusher',
    name: 'Skull crushers',
    muscleGroup: 'triceps',
    equipment: ['bench', ['dumbbells', 'barbell']],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 12, 15],
    animation: 'skullCrusher',
    steps: [
      'Lig på bænken med vægten strakt op over brystet.',
      'Bøj kun i albuerne, og sænk vægten mod panden.',
      'Stræk armene igen.',
    ],
    tip: 'Overarmene skal stå stille – kun underarmene bevæger sig.',
  },
  {
    id: 'overheadTricepsExtension',
    name: 'Triceps over hovedet',
    muscleGroup: 'triceps',
    equipment: ['dumbbells'],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 12, 15],
    animation: 'overheadTricepsExtension',
    steps: [
      'Hold én håndvægt med begge hænder strakt over hovedet.',
      'Bøj albuerne, og sænk vægten ned bag hovedet.',
      'Stræk armene op igen.',
    ],
    tip: 'Hold albuerne pegende fremad og tæt på hovedet.',
  },
  {
    id: 'concentrationCurl',
    name: 'Koncentrationscurl',
    muscleGroup: 'biceps',
    equipment: ['bench', 'dumbbells'],
    unit: 'perSide',
    sideLabel: 'pr. arm',
    difficulty: 1,
    amounts: [8, 10, 12, 15],
    animation: 'concentrationCurl',
    steps: [
      'Sid på bænken, og læn dig frem med albuen mod indersiden af låret.',
      'Curl håndvægten op mod skulderen.',
      'Sænk langsomt, og skift arm.',
    ],
    tip: 'Albuen bliver mod låret hele tiden, så det ikke er skulderen, der løfter.',
  },
  {
    id: 'dumbbellRDL',
    name: 'Rumænsk dødløft med håndvægte',
    muscleGroup: 'legs',
    equipment: ['dumbbells'],
    unit: 'reps',
    difficulty: 2,
    amounts: [8, 10, 12, 15],
    animation: 'dumbbellRDL',
    steps: [
      'Stå med en håndvægt i hver hånd foran lårene og let bøjede knæ.',
      'Skub hoften bagud, og før vægtene ned langs benene med lige ryg.',
      'Stop, når baglårene strækker, og rejs dig op.',
    ],
    tip: 'Træner baglår og balder. Hold ryggen lige hele vejen.',
  },
  {
    id: 'bandRow',
    name: 'Roning med elastik',
    muscleGroup: 'back',
    equipment: ['resistanceBand'],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 12, 15, 20],
    animation: 'bandRow',
    steps: [
      'Sid på gulvet med strakte ben og elastikken om fødderne.',
      'Træk hænderne ind mod maven med albuerne tæt på kroppen.',
      'Klem skulderbladene sammen, og slip langsomt.',
    ],
    tip: 'Sid rank – læn dig ikke bagud for at trække.',
  },
  {
    id: 'bandFacePull',
    name: 'Face pulls med elastik',
    muscleGroup: 'posture',
    equipment: ['resistanceBand'],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 12, 15, 20],
    animation: 'bandFacePull',
    steps: [
      'Fastgør elastikken i ansigtshøjde, fx i et dørhåndtag eller en dørkarm.',
      'Træk den mod ansigtet med albuerne højt og ud til siden.',
      'Klem skulderbladene sammen, og slip langsomt.',
    ],
    tip: 'En af de bedste øvelser mod fremadrullede skuldre.',
  },
  {
    id: 'bandPushdown',
    name: 'Triceps pushdown med elastik',
    muscleGroup: 'triceps',
    equipment: ['resistanceBand'],
    unit: 'reps',
    difficulty: 1,
    amounts: [10, 15, 20, 25],
    animation: 'bandPushdown',
    steps: [
      'Fastgør elastikken højt oppe, fx i toppen af en dør.',
      'Hold albuerne ind til siden, og pres hænderne ned, til armene er strakte.',
      'Slip langsomt op igen.',
    ],
    tip: 'Kun underarmene bevæger sig.',
  },
];

module.exports = { EXERCISES };
